# Stage 1: Build
FROM maven:3.9-eclipse-temurin-17 AS build
COPY . /app
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libheif-examples \
    imagemagick \
    && rm -rf /var/lib/apt/lists/*

RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:17-jre-alpine

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
# Create the upload directory inside the container
RUN mkdir -p /app/uploads && chmod 755 /app/uploads
RUN chown spring:spring /app/uploads
ENTRYPOINT ["java", "-Xmx512m", "-jar", "app.jar"]