app.frontend.url=${FRONTEND_URL:http://localhost:5173}

# Max size for a single file
spring.servlet.multipart.max-file-size=${UPLOAD_FILE_MAX_SIZE:5MB}

# Max size for the entire multipart request (multiple files)
spring.servlet.multipart.max-request-size=${UPLOAD_REQUEST_MAX_SIZE:10MB}

# Upload directory location
app.image.upload-directory=${UPLOAD_DIRECTORY:/app/uploads/}

# Delete file after particular times (seconds)
app.image.delete-after=${DELETE_FILE_AFTER:60}